<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\core\ApiServices\Visitor.Core.Db\Visitor.Core.Db.csproj" />
    <ProjectReference Include="..\Visitor.Module.IAM.Domain\Visitor.Module.IAM.Domain.csproj" />
  </ItemGroup>

</Project>
